mqtt:
  host: 192.168.1.64
  port: 1883
  user: frigate
  password: frigate
  topic_prefix: frigate
cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://admin:satanas@192.168.1.250:554/h264Preview_01_main
          roles:
            - detect
            - rtmp
            - record

    detect:
      width: 1280
      height: 720
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
